server:
    port: 8080

spring:
    influxdb:
        url: http://influx:8086
        username: tanu
        password: password
        database: metricsData

clientUrl: http://client:8082
containerUrl: "http://172.23.239.222:9001"
cpuCoresInterval: 10000
cpuTempInterval: 10000
cpuUsageInterval: 10000
networkInterval: 10000
threadInterval: 10000
diskInterval: 10000
ramInterval: 10000
healthInterval: 1000
httpInterval: 10000
containerInterval: 10000